
[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.6.0"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "39.0.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
